# Generated by Django 3.2.13 on 2022-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2022-6-28'),
            preserve_default=False,
        ),
    ]
