# Generated by Django 3.2.13 on 2022-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_requestforservice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforservice',
            name='verification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
