# Generated by Django 3.2.13 on 2022-07-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_requestforservice_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforservice',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.verificationstatus'),
        ),
    ]
