# Generated by Django 3.2.13 on 2022-07-17 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_requestforservice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestforservice',
            old_name='date_created',
            new_name='job_date',
        ),
    ]
