# Generated by Django 3.2.13 on 2022-07-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_requestforservice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforservice',
            name='location',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requestforservice',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
