# Generated by Django 3.2.13 on 2022-07-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20220722_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='title',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
