# Generated by Django 3.2.13 on 2022-07-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220722_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotifications',
            name='title',
        ),
    ]
