# Generated by Django 3.2.13 on 2022-07-22 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_serviceassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestforservice',
            old_name='user',
            new_name='requested_by',
        ),
        migrations.AddField(
            model_name='requestforservice',
            name='assigned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestforservice',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
