# Generated by Django 3.2.13 on 2022-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_requestforservice_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforservice',
            name='requested_by',
            field=models.EmailField(max_length=100),
        ),
    ]
