# Generated by Django 3.2.13 on 2022-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_requestforservice_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforservice',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
